import assert from 'node:assert/strict';
import gameState from '../src/app/GameState.js';
import Manager from '../src/app/MacromolecularizerManager.js';
import Catalog from '../src/data/MacromolecularRecipeCatalog.js';
const store=new Map();globalThis.localStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
gameState.discoveries.reactions={dehydration:{discoveredAt:1}};
gameState.registry.resources.atp={current:50,maximum:50};
gameState.zones.moleculeLab.state={synthesized:{}};
gameState.zones.macromolecularizer.state={};Manager.initialize();
const d=Catalog.get('AcetylCoA');assert.equal(d.category,'nucleotides');assert.equal(d.bondType,'thioester');assert.equal(d.atpCost,1);assert.equal(d.baseDurationSeconds,30);
assert.equal(Manager.getMotifEligibility('AcetylCoA').canStart,false);
Manager.ensureState().motifInventory.CoA=1;
assert.equal(Manager.getMotifEligibility('AcetylCoA').canStart,false,'acetic acid knowledge is required');
const cleared=Manager.ensureState();delete cleared.motifInventory.CoA;delete cleared.synthesized.CoA;gameState.zones.moleculeLab.state.synthesized.AceticAcid={count:1};
assert.equal(Manager.getMotifEligibility('AcetylCoA').canStart,false,'completed CoA is required');
Manager.ensureState().motifInventory.CoA=1;assert.equal(Manager.getMotifEligibility('AcetylCoA').canStart,true);
const precursorSnapshot=structuredClone(gameState.zones.moleculeLab.state.synthesized),atp=gameState.registry.resources.atp.current;
const result=Manager.startSynthesis('AcetylCoA',1000);assert.equal(result.success,true);
assert.equal(gameState.registry.resources.atp.current,atp-1);
const job=Manager.ensureState().activeSynthesis;
assert.equal(job.motifId,'AcetylCoA');assert.equal(Manager.finishSynthesis(job.jobId,job.completesAtMs).success,true);
assert.equal(Manager.ensureState().motifInventory.AcetylCoA,1);assert.equal(Manager.ensureState().motifInventory.CoA,1);assert.deepEqual(gameState.zones.moleculeLab.state.synthesized,precursorSnapshot);
assert.equal(JSON.parse(store.get('ECGame_Save')).zones.macromolecularizer.state.motifInventory.AcetylCoA,1);
console.log('PASS: N-tab acetyl-CoA requires CoA and acetic acid, charges one game ATP, preserves precursor knowledge and saves completed inventory.');
