import assert from 'node:assert/strict';
import fs from 'node:fs';
import Recipes from '../src/data/PolymerizerRecipeCatalog.js';
import Visuals from '../src/data/PolymerizerVisualCatalog.js';
import {ProteinAssemblyPractice} from '../src/app/ProteinAssemblyPractice.js';
import gameState from '../src/app/GameState.js';
import Manager from '../src/app/PolymerizerManager.js';
import Resources from '../src/app/ResourceManager.js';
const store=new Map();globalThis.localStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
const rows=fs.readFileSync(new URL('../docs/data/1pg4-motifs.csv',import.meta.url),'utf8').trim().split(/\r?\n/).slice(1).map(r=>r.split(','));
const d=Recipes.get('AcetylCoASynthetase'),v=Visuals.get(d.id);assert.equal(d.valid,true);assert.equal(d.implemented,true);assert.equal(d.simplifiedStructure,rows.map(r=>r[5]).join(''));
assert.equal(d.atpCost,99);assert.equal(d.assemblyDurationMs,39750);assert.equal(d.discoveryId,null);assert.equal(v.displayZoomPercent,230);assert.equal(v.frameCount,48);
assert.match(v.idleImageUrl,/1pg4-0\.webp$/);assert.match(v.finalImageUrl,/1pg4-47\.webp$/);
const before=structuredClone(gameState),practice=new ProteinAssemblyPractice(d.id);practice.start(null,100);practice.tick(8100);assert.equal(practice.full,true);assert.equal(practice.imageUrl(),v.finalImageUrl);assert.deepEqual(gameState,before);
gameState.zones.polymerizer.state={productInventory:{},activeAssembly:null};gameState.zones.macromolecularizer.state.motifInventory={H_helix:25,B_sheet:30,L_loop:44};Resources.setATPStatus({current:200,maximum:1000},'test');
const discoveries=structuredClone(gameState.discoveries),achievements=structuredClone(gameState.registry.achievements),metabolism=structuredClone(gameState.zones.metabolism);
const r=Manager.startAssembly(d.id,1000);assert.equal(r.success,true);assert.equal(Resources.getATPStatus().current,101);assert.equal(Manager.finishAssembly(r.activeAssembly.jobId,r.activeAssembly.completesAtMs).success,true);
assert.equal(Manager.ensureState().productInventory[d.id].count,1);assert.deepEqual(gameState.discoveries,discoveries);assert.deepEqual(gameState.registry.achievements,achievements);assert.deepEqual(gameState.zones.metabolism,metabolism);
console.log('PASS: exact fresh 1PG4 recipe, frame zero, 48 images, 120% zoom, isolated practice and normal synthesis without pathway or achievement grants.');
