import assert from "node:assert/strict";
import gameState from "../src/app/GameState.js";
import { proteinLibrary } from "../src/data/proteinLibrary.js";
import PolymerizerRecipeCatalog from "../src/data/PolymerizerRecipeCatalog.js";
import PolymerizerVisualCatalog from "../src/data/PolymerizerVisualCatalog.js";
import PolymerizerManager from "../src/app/PolymerizerManager.js";

const before = structuredClone(gameState);
const protein = proteinLibrary.RuBisCO;
const recipe = PolymerizerRecipeCatalog.get("RuBisCO");
const visual = PolymerizerVisualCatalog.get("RuBisCO");
assert.equal(protein.Source, "9HVM");
assert.deepEqual(protein.Recipe, { H: 190, B: 136, L: 310 });
assert.equal(recipe.motifCount, 636);
assert.equal(recipe.valid, true);
assert.equal(recipe.structureOrderKnown, true, "motif order comes from the full supplied CSV");
assert.equal(recipe.implemented, true, "real synthesis now supports components with normal resource checks");
assert.equal(recipe.atpCost, 636);
assert.equal(recipe.discoveryId, null);
assert.equal(recipe.unlockDiscoveryId, null);
assert.equal(recipe.completionQuestId, null);
assert.equal(visual.frameCount, 345);
assert.equal(visual.assemblyFrameCount, 344);
assert.match(visual.idleImageUrl, /9hvm_motifs\/9hvm-0\.webp$/);
assert.match(visual.finalImageUrl, /9hvm_motifs\/9hvm-344\.webp$/);
assert.deepEqual(gameState, before, "reading catalogs never modifies player state");
const eligibility = PolymerizerManager.getProductEligibility("RuBisCO");
assert.equal(eligibility.canStart, false, "normal assembly still requires sufficient real motifs and ATP");
assert.deepEqual(gameState.registry.discoveries, before.registry.discoveries);
assert.deepEqual(gameState.registry.resources, before.registry.resources);
console.log("PASS: 9HVM RuBisCO recipe, real component support, and 345 frames are registered without adding discoveries/resources.");
