import assert from 'node:assert/strict';
import fs from 'node:fs';
import gameState from '../src/app/GameState.js';
import ResourceManager from '../src/app/ResourceManager.js';
import SaveManager from '../src/app/SaveManager.js';
import Observer from '../src/app/GameStateObserver.js';
import Manager from '../src/app/PolymerizerManager.js';
import Components from '../src/app/PolymerizerComponentManager.js';
import Recipes from '../src/data/PolymerizerRecipeCatalog.js';
import {ProteinAssemblyPractice} from '../src/app/ProteinAssemblyPractice.js';
import CalvinPractice from '../src/app/CalvinPracticeManager.js';
import {dockFixationInput,beginFixation,finishFixation,storeFixationProducts,advanceFixation,answerFixation} from '../src/app/CalvinFixationModel.js';
import {groupPolymerizerProducts} from '../src/app/PolymerizerProductView.js';

const store=new Map();let writes=0, completions=0;
globalThis.localStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>{writes++;store.set(k,String(v));},removeItem:k=>store.delete(k)};
Observer.on('polymerizer-product-completed',p=>{if(p.productId==='RuBisCO')completions++;});
gameState.zones.polymerizer.state={productInventory:{},activeAssembly:null,unrelated:{keep:true}};
gameState.zones.macromolecularizer.state.motifInventory={H_helix:20,B_sheet:13,L_loop:30};
ResourceManager.setATPStatus({current:1500,maximum:2000},'test');
const recipe=Recipes.get('RuBisCO');
assert.equal(recipe.motifCount,636);
assert.equal(recipe.components.length,16);
assert.equal(recipe.purpose,'Calvin Cycle');
assert.equal(Recipes.get('Glycerol3PhosphateAcyltransferase').purpose,'Lipid Synthesis');
const csv=fs.readFileSync(new URL('../docs/data/9hvm-motifs.csv',import.meta.url),'utf8').trim().split(/\r?\n/).slice(1).map(line=>line.split(','));
assert.equal(csv.map(row=>row[5]).join(''),recipe.simplifiedStructure);
for(const c of recipe.components){
 const rows=csv.filter(r=>r[1]===c.sourceModel && r[3]===c.sourceChain);
 assert.equal(rows.length,Object.values(c.recipe).reduce((a,b)=>a+b));
 for(const symbol of ['H','B','L'])assert.equal(rows.filter(r=>r[5]===symbol).length,c.recipe[symbol]);
 assert.equal(Number(rows.at(-1)[9]),c.lastFrame);
}
const beforePractice=JSON.stringify(gameState),beforeWrites=writes;
const practice=new ProteinAssemblyPractice('RuBisCO');
assert.equal(practice.start(2,100),false,'cumulative assets preserve numbered order');
assert.equal(practice.start(1,100),true);
assert.match(practice.imageUrl(8100),/9hvm-33\.webp$/);
practice.tick(8100);assert.deepEqual(practice.completedIds,[1]);
assert.equal(practice.start(null,8200),true);practice.tick(16200);
assert.equal(practice.full,true);assert.match(practice.imageUrl(),/9hvm-344\.webp$/);
CalvinPractice.start();
const s=CalvinPractice.session;dockFixationInput(s,'RuBisCO');
for(let i=0;i<3;i++){dockFixationInput(s,'RuBP');dockFixationInput(s,'CO2');beginFixation(s);dockFixationInput(s,'H2O');finishFixation(s);storeFixationProducts(s);advanceFixation(s);}
assert.equal(answerFixation(s,'CO2'),true);assert.equal(CalvinPractice.complete().success,true);CalvinPractice.reset();
const afterPractice=structuredClone(gameState);
assert.equal(afterPractice.zones.metabolism.state.practiceMastery.RuBisCO.scorePercent,100);
delete afterPractice.zones.metabolism.state.practiceMastery;
afterPractice.saveMetadata=JSON.parse(beforePractice).saveMetadata;
assert.equal(JSON.stringify(afterPractice),beforePractice,'only the educational P marker changes');
assert.ok(writes>beforeWrites,'perfect Calvin practice saves its marker');
assert.equal(completions,0);
assert.equal(Manager.getProductEligibility('RuBisCO').canStart,false,'whole complex levels are unmet');
assert.equal(Components.getStatus('RuBisCO',1).canStart,true,'component has smaller requirements');
assert.equal(Components.start('RuBisCO',2,100).success,false);
const save=SaveManager.save;SaveManager.save=()=>false;
const beforeATP=ResourceManager.getATPStatus();
assert.equal(Components.start('RuBisCO',1,100).reason,'save-failed');
assert.deepEqual(ResourceManager.getATPStatus(),beforeATP);
assert.equal(Manager.ensureState().activeAssembly,null);
SaveManager.save=save;
let start=Components.start('RuBisCO',1,1000);assert.equal(start.success,true);
assert.equal(start.activeAssembly.atpCost,63);
assert.equal(ResourceManager.getATPStatus().current,1437);
assert.equal(Components.start('RuBisCO',1,1001).success,false);
assert.equal(Manager.finishAssembly(start.activeAssembly.jobId,1001).reason,'assembly-not-complete');
// Reload a paid component job through the existing normalizer.
gameState.zones.polymerizer.state=JSON.parse(store.get('ECGame_Save')).zones.polymerizer.state;
assert.deepEqual(Manager.getActiveAssemblyProgress(1001).componentIds,[1]);
SaveManager.save=()=>false;
assert.equal(Manager.finishAssembly(start.activeAssembly.jobId,start.activeAssembly.completesAtMs).reason,'save-failed');
assert.equal(Manager.getActiveAssemblyProgress(1001).jobId,start.activeAssembly.jobId);
assert.equal(gameState.zones.polymerizer.state.componentAssemblies,undefined);
assert.equal(gameState.zones.polymerizer.state.productInventory.RuBisCO,undefined);
SaveManager.save=save;
assert.equal(Manager.finishAssembly(start.activeAssembly.jobId,start.activeAssembly.completesAtMs).success,true);
let status=Manager.getProductEligibility('RuBisCO');
assert.equal(status.componentProgress.completedCount,1);
assert.equal(status.componentProgress.frame,33);
assert.equal(status.atp.cost,573,'full-complex cost excludes finished component');
assert.equal(status.definition.motifCount,636,'protein level remains full-complex level');
assert.equal(status.output.quantity,0,'partial components grant no usable enzyme');
assert.equal(completions,0,'partial completion triggers no downstream full-product event');
assert.equal(groupPolymerizerProducts([status])[0].id,'components');
assert.equal(Components.start('RuBisCO',1,50000).success,false,'duplicate component is blocked');
assert.equal(Components.getStatus('RuBisCO',2).plan.atpCost,15);
// Completing the remainder checks the remaining counts, not the original full recipe.
gameState.zones.macromolecularizer.state.motifInventory={H_helix:170,B_sheet:123,L_loop:280};
const motifsBefore=structuredClone(gameState.zones.macromolecularizer.state.motifInventory);
const discoveriesBefore=[...gameState.registry.discoveries];
start=Manager.startAssembly('RuBisCO',50000);assert.equal(start.success,true);
assert.equal(start.activeAssembly.atpCost,573);
assert.deepEqual(start.activeAssembly.componentIds,Array.from({length:15},(_,i)=>i+2));
assert.equal(ResourceManager.getATPStatus().current,864);
SaveManager.save=()=>false;
assert.equal(Manager.finishAssembly(start.activeAssembly.jobId,start.activeAssembly.completesAtMs).reason,'save-failed');
assert.deepEqual(gameState.zones.polymerizer.state.componentAssemblies.RuBisCO.completedIds,[1]);
assert.equal(gameState.zones.polymerizer.state.productInventory.RuBisCO,undefined);
SaveManager.save=save;
assert.equal(Manager.finishAssembly(start.activeAssembly.jobId,start.activeAssembly.completesAtMs).success,true);
assert.equal(Manager.getProductEligibility('RuBisCO').completion.source,'synthesized');
assert.equal(Manager.ensureState().productInventory.RuBisCO.count,1);
assert.equal(completions,1);
assert.equal(Manager.finishAssembly(start.activeAssembly.jobId,start.activeAssembly.completesAtMs).success,false);
assert.equal(Manager.startAssembly('RuBisCO',200000).success,false);
assert.deepEqual(gameState.registry.discoveries,discoveriesBefore);
assert.deepEqual(gameState.zones.macromolecularizer.state.motifInventory,motifsBefore);
assert.deepEqual(gameState.zones.polymerizer.state.unrelated,{keep:true});
assert.equal(writes>beforeWrites,true);
console.log('PASS: exact numbered CSV components, lower per-component requirements, paid reload-safe jobs, partial/full rollback, remaining cost, one full product event, purpose labels, and completely isolated assembly/Calvin practice.');
