// Generated by tools/setup-instructor-recovery-key.mjs.
// The public key is safe to commit. Never commit the matching private PEM file.
const InstructorRecoveryPublicKey = {
    keyId: "694a66081b0157e5",
    spkiBase64: "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEI+znzPVxcJfYGeK1CIj9Ovzgbkq6SQ+0KJ5IzpiSNSPRQDe7vNLU1YzuxSwCRj5PVMARSnIK/qPdrZkfa/HvGA=="
};

export default InstructorRecoveryPublicKey;
